### ISSUE TITLE
pytube.exceptions.VideoPrivate: --bO6XwZ9HI is a private video is a private video

### ISSUE THREAD

**Issue by hongbo-miao** [neuroailab/VIE#25]
When I try to run

```shell
python3 download_videos.py --csv_path kinetics400/train.csv --save_dir data --save_raw_dir raw_data --len_idx 246535
```

I got error

```
  0%|                                                                       | 13/219782 [00:15<73:01:04,  1.20s/it]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "download_videos.py", line 118, in download_one_video
    video = yt.streams.filter(
  File "/home/hongbo_miao/.local/lib/python3.7/site-packages/pytube/__main__.py", line 307, in streams
    self.check_availability()
  File "/home/hongbo_miao/.local/lib/python3.7/site-packages/pytube/__main__.py", line 267, in check_availability
    raise exceptions.VideoPrivate(video_id=self.video_id)
pytube.exceptions.VideoPrivate: --bO6XwZ9HI is a private video
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "download_videos.py", line 190, in <module>
    main()
  File "download_videos.py", line 186, in main
    multi_process_download(args, csv_data, curr_len)
  File "download_videos.py", line 173, in multi_process_download
    total=curr_len))
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
pytube.exceptions.VideoPrivate: --bO6XwZ9HI is a private video is a private video
```

Is this error related with `pytube` version? I am using pytube 10.7.2.
May I know which `pytube` version you are using? Thanks

**Comment by chengxuz** [comment]
Hi Hongbo, I believe I was using version 9.6.0, not super certain though. Regardlessly, I think you can easily fix this bug. The main problem is that some of the videos in the list are no longer available. You can see that I handled this situation in line 104 and 126 (just skip the videos if not available). You can also do similar things in this sentence (line 118).

**Comment by hongbo-miao** [comment]
Thanks for the info @chengxuz !
