### ISSUE TITLE
Minimal example of loading checkpoints

### ISSUE THREAD

**Issue by patrickmineault** [neuroailab/VIE#26]
I've tried to load the checkpoint linked in the README using run_finetune_HMDB.sh as a template. After patching up some errors and hardcoding the checkpoint location in framework.py, I get this error during the restore process:

```
Restore from /content/video_pub_cache/models/vd_finetune/HMDB/vd_3dresnet_sc/model.ckpt
2021-05-22 05:01:02.960066: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key instance/transfer_dense/bias not found in checkpoint
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
  (0) Not found: Key instance/transfer_dense/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key instance/transfer_dense/bias not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_133]]
0 successful operations.
0 derived errors ignored.
```

Could you show a minimal example of creating a model of the correct architecture and loading the pretrained checkpoint?

**Comment by chengxuz** [comment]
hey Patrick, 

sorry for being slow on this, I am happy to help, can you let me know what you want to load the pretrained ckpt to do? Like getting its responses on some videos?

Best,
Chengxu

**Comment by patrickmineault** [comment]
Yes I'd like to measure the response to videos in intermediate layers.

**Comment by chengxuz** [comment]
Sorry for being slow. I have just updated the repo, please check the new readme. Let me know if you have further questions.

**Comment by patrickmineault** [comment]
Looks great, thanks!
